# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveStraming' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveStraming
  pod 'Socket.IO-Client-Swift', '~> 12.0.0'
  pod 'LFLiveKit', '~> 2.6'
  pod 'IJKMediaFramework'
end
